### ISSUE TITLE
Refactor: merging fails with fba_run used --write_all_targets

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#164]
When `fba_run` uses the `--write_all_targets` option, `fba_merge_results` fails with tracebacks like
```
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/global/cscratch1/sd/sjbailey/desi/code/fiberassign/py/fiberassign/assign.py", line 831, in merge_results_tile
    targets_data[field][target_rows]
ValueError: shape mismatch: value array of shape (7191,) could not be broadcast to indexing result of shape (837,)
```

**Comment by tskisner** [comment]
I believe this was fixed in 084f153fd0bf11843fb732fff5c43e1f83bd3148.
