### ISSUE TITLE
refactor: incompatible constructor arguments error

### ISSUE THREAD

**Issue by forero** [desihub/fiberassign#172]
Running this tutorial https://github.com/desihub/tutorials/blob/master/FiberAssign.ipynb with the refactor version and gives me the following error

```
 RUNNING: fiberassign --mtl mtl.fits --stdstar stdstars.fits --sky sky.fits --footprint ./tiles.fits --outdir ./output/
INFO: sciencemask LRG ELG QSO BAD_SKY BGS_ANY MWS_ANY SECONDARY_ANY
INFO: stdmask     STD_FAINT STD_WD STD_BRIGHT
INFO: skymask     SKY
INFO: safemask    BAD_SKY
INFO: excludemask BRIGHT_OBJECT IN_BRIGHT_OBJECT
INFO: Reading fiber positions from /global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desimodel/0.9.9/data/focalplane/fiberpos-all.fits
Traceback (most recent call last):
  File "/global/homes/f/forero/fiberassign/bin/fba_run", line 299, in <module>
    main()
  File "/global/homes/f/forero/fiberassign/bin/fba_run", line 198, in main
    tiles = load_tiles(hw, tiles_file=args.footprint, select=tileselect)
  File "/global/homes/f/forero/fiberassign/py/fiberassign/tiles.py", line 31, in load_tiles
    tiles_data["OBSCONDITIONS"][keeprows])
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. fiberassign._internal.Tiles(arg0: fiberassign._internal.Hardware, arg1: List[int], arg2: List[float], arg3: List[float], arg4: List[int])

Invoked with: <fiberassign._internal.Hardware object at 0x2aaac3659ae8>, array([0, 1, 2, 3, 4]), array([ 2.        ,  2.80288675,  3.6057735 ,  4.40866025,  5.211547  ]), array([ 0.,  0.,  0.,  0.,  0.]), array([ 1.,  1.,  1.,  1.,  1.])
1
```
I guess it has to do with conflicting data types, but I am not sure what should I change in the input data.

**Comment by tskisner** [comment]
I'll investigate- that may be my fault not updating the fiberassign legacy wrapper when changing another interface.

**Comment by tskisner** [comment]
Hmmm, does your tiles.fits file have an OBSCONDITIONS column?  That is required for the footprint files, but in the target files it is optional- target files without this column are assumed to have targets valid for any tile OBSCONDITIONS.

**Comment by forero** [comment]
Yes, they do have an OBSCONDITIONS column. The tiles are initialized in cell [3]: https://github.com/desihub/tutorials/blob/master/FiberAssign.ipynb

**Comment by sbailey** [comment]
I just updated the tutorials repo; the FiberAssign.ipynb tutorial there now works with both master and the tsk_refactor branch.
