### ISSUE TITLE
Inconsistent behaviour for duplicate IDs across Science targets & standards 

### ISSUE THREAD

**Issue by michaelJwilson** [desihub/fiberassign#198]
survey-tiles file (single tile with ID 100000):

![image](https://user-images.githubusercontent.com/6034066/57560449-59e5ae00-733b-11e9-9f87-c836614ffae0.png)

Footprint file (Kyle's BGS tiling):

![image](https://user-images.githubusercontent.com/6034066/57560948-ff018600-733d-11e9-8911-b8fad10d5564.png)

Call:

```
fiberassign 

--mtl /global/cscratch1/sd/mjwilson/svdc-summer2018/targets/mtl.fits 
--stdstar /global/cscratch1/sd/mjwilson/svdc-summer2018/targets/standards-dark.fits 
--sky /global/cscratch1/sd/mjwilson/svdc-summer2018/targets/sky.fits  
--surveytiles ~mjwilson/desi/survey-validation/svdc-summer2018/bgs-gama-tiles-kdawson_100000.txt  
--footprint ~mjwilson/desi/survey-validation/svdc-summer2018/bgs-gama-tiles-kdawson.fits 
--fibstatusfile /global/homes/m/mjwilson/desi/survey-validation/svdc-summer2018/fiberstatus.ecsv 
--outdir /global/cscratch1/sd/mjwilson/svdc-summer2018/fiberassign
```

Error message: 

![image](https://user-images.githubusercontent.com/6034066/57560502-a3ce9400-733b-11e9-93ab-52e15d311fc8.png)

Failure to over-ride default footprint with --footprint?  These directories have desi permissions for reproducing the error. 

Background (file production) is here:
https://github.com/michaelJwilson/survey-validation/blob/master/svdc-summer2018/bgs-gama-pipeline.ipynb

but I'm running fiberassign in the shell to test.

**Comment by sbailey** [comment]
This example works with fiberassign/1.0.0, i.e. it looks like the bug you report here is already fixed.  You can switch to this at NERSC with `module swap fiberassign/1.0.0`.

However, I will leave this ticket open since your example crashes with fiberassign/master for a different reason (that isn't your fault):
```
ERROR:   Duplicate target IDs are not permitted.
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/bin/fiberassign", line 107, in <module>
    run_assign_full(assign_args)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/py/fiberassign/scripts/assign.py", line 300, in run_assign_full
    hw, tiles, tgs = run_assign_init(args)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/py/fiberassign/scripts/assign.py", line 266, in run_assign_init
    excludemask=args.excludemask)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/py/fiberassign/targets.py", line 642, in load_target_file
    excludemask=excludemask)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/py/fiberassign/targets.py", line 571, in load_target_table
    stdmask, skymask, safemask, excludemask)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/py/fiberassign/targets.py", line 414, in append_target_table
    d_subprior, d_obscond, d_type)
RuntimeError:   Duplicate target IDs are not permitted.
```

A quick spot check shows that these are standards that are also appearing as science targets in the mtl file.  Although the low-level fba_run code doesn't allow duplicate IDs across different input files, the high-level backwards compatible `fiberassign` script should support that (but apparently doesn't).  In this case the standards are completely a subset of mtl and shouldn't be needed at all, but the `fiberassign` wrapper still requires the file and will crash if it isn't provided.
