### ISSUE TITLE
QA-FIBERASSING ON SV SIM. 

### ISSUE THREAD

**Issue by michaelJwilson** [desihub/fiberassign#205]
Running qa-fiberassign on the SV sim. results in the following error:

```
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/fiberassign/master/bin/qa-fiberassign", line 74, in <module>
    num_no_desitarget = np.count_nonzero(fa['DESI_TARGET'] == 0)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/table/table.py", line 1222, in __getitem__
    return self.columns[item]
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/table/table.py", line 109, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'DESI_TARGET'
```

seems a straightforward fix (to rewrite DESI_TARGET expectation) see fiberassign itself.  I'll look at it, but maybe someone (@forero?) will beat me to it ... 

Also a --outputdir argument would help?

**Comment by tskisner** [comment]
This "qa-fiberassign" script is copied from the original legacy codebase.  We should consider merging this functionality with the fba_run_qa / fba_plot_qa scripts, which generate a json document with assignment stats for each tile and also visualizes those values on the footprint.

**Comment by forero** [comment]
After running `fba_run_qa` on the SV data I get the following

```
INFO: Reading fiber positions from /global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desimodel/master/da
ta/focalplane/fiberpos-all.fits
INFO: Found 91 fiberassign tile files
INFO: Selecting 0 fiberassign tile files
```
and an empty `qa.json` file. 

What is then the correct way to call the script?

**Comment by michaelJwilson** [comment]
I think it's failing because of the sv tile ids.  Adding --footprint works, but achieves another error.

```
fba_run_qa --dir /global/cscratch1/sd/mjwilson/svdc2019c/fiberassign --out /global/cscratch1/sd/mjwilson/svdc2019c/fiberassign-qa/qa.json --footprint /global/cscratch1/sd/mjwilson/svdc2019c/survey/SV-tiles.fits
```

**Comment by forero** [comment]
Got it. Thanks.

**Comment by michaelJwilson** [comment]
I was looking at:

https://desi.lbl.gov/DocDB/cgi-bin/private/RetrieveFile?docid=4247;filename=FiberAssignment_Dawson_Barcelona.pdf;version=1

It'd be great to have a follow-up based on this SV set.  Not least, I think Stephen wanted checks that things hadn't gone awry.

**Comment by forero** [comment]
I will take that as guide to prepare a short report.

**Comment by Srheft** [comment]
Hi @forero:
Any update on this ticket? qa-fiberassign would need to work on CMX as well and the blocking factor seems to be the unrecognizable objtype.

**Comment by forero** [comment]
Hi @Srheft. Nothing new, `fba_run_qa` works but the older `qa_fiberassign` does not. To me the best solution seems to be implementing the `qa_fiberassign` stats inside`fba_run_qa` and avoid using `DESI_TARGET` (`OBJTYPE` does the work to count science,sky and stars). I will only have time to tackle this in August.

**Comment by Srheft** [comment]
ok; thanks for the info; fba_run_qa and fiberassign-qa both have useful info. I'll give it shot to work to our taste for cmx/sv.
