### ISSUE TITLE
writing error with small number of targets

### ISSUE THREAD

**Issue by forero** [desihub/fiberassign#251]
I am trying to create a small unit test for fiberassign. For that I created two tiles, and mtl file 8 science targets and a sky file with 8 sky targets. 

The files I am using are in this repo https://github.com/forero/issue_fiberassign

After running running the command

```
fiberassign --overwrite --mtl mtl.fits --sky sky.fits --footprint ./tiles.fits --outdir ./
```

the following error appears

```
INFO: Writing tile 0
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/bin/fiberassign", line 151, in <module>
    run_assign_full(assign_args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/py/fiberassign/scripts/assign.py", line 400, in run_assign_full
    gfa_targets=gfa_targets, overwrite=args.overwrite)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/py/fiberassign/assign.py", line 526, in write_assignment_fits
    write_tile(params)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/py/fiberassign/assign.py", line 337, in write_assignment_fits_tile
    target_rows = [tg_indx[x] for x in assigned_real]
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/fiberassign/master/py/fiberassign/assign.py", line 337, in <listcomp>
    target_rows = [tg_indx[x] for x in assigned_real]
KeyError: 0

```

The problem seems to be with some empty file, but at least one target should be assigned. Any idea how to solve this?

**Comment by forero** [comment]
Solved by making the TILEID different from 0 or 1 (!).
